import { open, settle, toggleLibrary, ROOT } from './lib.mjs';
import { writeFileSync } from 'node:fs';
const P = ROOT + '/docs/guides/screenshots/callouts/_probeG/';
const { browser, page } = await open();
page.on('request', r => { if (/notation|lyrics|lyricanalysis/.test(r.url())) console.log('REQ', r.method(), r.url()); });
const dump = async (name) => {
  await page.screenshot({ path: P + name + '.png' });
  const info = await page.evaluate(() => [...document.querySelectorAll('button,[role=slider],[role=tab],[role=listbox],[role=option],input,select,canvas,svg,textarea,[title],[aria-label],[contenteditable]')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.y<1080&&r.y>=0}).map(e=>{const r=e.getBoundingClientRect();return `${e.tagName} role=${e.getAttribute('role')||''} t=${(e.title||'').slice(0,50)} a=${e.getAttribute('aria-label')||''} txt=${(e.textContent||'').trim().slice(0,40)} @${r.x|0},${r.y|0} ${r.width|0}x${r.height|0}`}).join('\n'));
  writeFileSync(P + name + '.txt', info);
};
const T={Score:'Sheet music',Sing:'Karaoke',Lyric:'Write, edit and analyse',Slide:'Control surface'};
const dockTab = (t) => page.locator(`button[title^="${T[t]}"]`).first();
await toggleLibrary(page);
if (!(await dockTab('Score').isVisible())) await page.getByRole('button',{name:'Expand bottom panel'}).click();
await settle(page, 1500);
await dockTab('Score').click();
await settle(page, 1500);
const rows = page.locator('div[title^="Click to inspect metadata"]').filter({hasText:'UrZunzet'});
const n = await rows.count();
const idx = Number(process.env.ROW ?? 1);
console.log('rows', n, 'using', idx);
await rows.nth(idx).click();
await page.getByRole('button',{name:'Maximize panel'}).first().click();
await settle(page, 8000);
await dump('SCORE');
await dockTab('Sing').click(); await settle(page, 6000); await dump('SING');
await dockTab('Lyric').click(); await settle(page, 4000); await dump('LYRIC');
await dockTab('Slide').click(); await settle(page, 4000); await dump('SLIDE');
await browser.close();
