import { open, settle, tab } from './lib.mjs';
const { browser, page } = await open();
page.on('console', m => { if (m.type()==='error') console.log('CONSOLE', m.text().slice(0,200)); });
await tab(page, 'VJ');
await page.waitForTimeout(20000);
const f = page.frames().find(fr => fr.url().includes('vj-app'));
console.log('frame', f?.url());
const r = await f.evaluate(() => [...document.querySelectorAll('button,[role=button],[aria-label],input,select,canvas,video,h1,h2,h3,[title]')].filter(e=>{const b=e.getBoundingClientRect();return b.width>0&&b.height>0}).map(e=>{const b=e.getBoundingClientRect();return `${e.tagName} a=[${e.getAttribute('aria-label')||''}] t=[${(e.getAttribute('title')||'').slice(0,50)}] "${(e.textContent||'').trim().replace(/\s+/g,' ').slice(0,30)}" @${Math.round(b.x)},${Math.round(b.y)} ${Math.round(b.width)}x${Math.round(b.height)}`}));
console.log(r.join('\n'));
console.log('TEXT', (await f.evaluate(()=>document.body.innerText)).slice(0,1500));
await page.screenshot({path:'../docs/guides/screenshots/callouts/raw/_probeD_VJ2.png'});
await browser.close();
