import assert from 'node:assert/strict';

import { summarizeEditor } from './appContext.ts';
import { useEditorStore } from '../state/editorStore.ts';

// A piano-roll clip is an AudioClip with sourceKind 'piano-roll' and an
// audio/wav blob (pre-rendered for playback). The summary must still call it
// MIDI — the label and mime type look exactly like audio.
const blob = new Blob([new Uint8Array(4)], { type: 'audio/wav' });
const base = useEditorStore.getState();
const snapshot = {
  ...base,
  bpm: 128,
  timeSignature: { num: 6, den: 8 },
  snap: '1/16' as const,
  tool: 'split' as const,
  selectedClipIds: ['ca', 'cm'],
  markers: [{ id: 'm1', t: 8.004, label: 'Chorus' }],
  tracks: [
    { id: 'ta', name: 'UrZunzet · full', nameAutoGenerated: false, volume: 1, pan: 0, mute: false, solo: false, color: '#fff' },
    { id: 'tm', name: 'UrZunzet · bass', nameAutoGenerated: false, volume: 0.8, pan: -0.2, mute: false, solo: true, color: '#fff', instrumentProgram: 33, armed: true },
    { id: 'te', name: 'Empty', nameAutoGenerated: true, volume: 1, pan: 0, mute: false, solo: false, color: '#fff' },
  ],
  clips: [
    { id: 'ca', trackId: 'ta', label: 'UrZunzet · full', audioBlob: blob, mimeType: 'audio/wav', sourceDuration: 30, offsetIntoSource: 0, durationSec: 30, startSec: 0, color: '#fff' },
    { id: 'cm', trackId: 'tm', label: 'UrZunzet · bass', audioBlob: blob, mimeType: 'audio/wav', sourceDuration: 30, offsetIntoSource: 0, durationSec: 30, startSec: 0.006, color: '#fff',
      sourceKind: 'piano-roll' as const, sourcePianoRoll: [{ pitch: 40, step: 0, length: 2, velocity: 100 }, { pitch: 43, step: 4, length: 2, velocity: 100 }] as never, sourceBpm: 128, instrumentProgram: 33 },
  ],
};

const s = summarizeEditor(snapshot as never);

assert.equal(s.trackCount, 3);
assert.equal(s.clipCount, 2);
assert.equal(s.midiClipCount, 1);
assert.equal(s.audioClipCount, 1);
assert.deepEqual(s.tracks.map((t) => t.kind), ['audio', 'midi', 'empty']);
assert.equal(s.tracks[1].instrumentProgram, 33);
assert.equal(s.tracks[1].armed, true);
assert.equal(s.clips[0].kind, 'audio');
assert.equal(s.clips[0].noteCount, null);
assert.equal(s.clips[1].kind, 'midi');
assert.equal(s.clips[1].noteCount, 2);
assert.equal(s.clips[1].instrumentProgram, 33);
assert.equal(s.clips[1].sourceBpm, 128);
assert.equal(s.clips[1].startSec, 0.01);
assert.equal(s.snap, '1/16');
assert.equal(s.tool, 'split');
assert.deepEqual(s.markers, [{ id: 'm1', sec: 8, label: 'Chorus' }]);
assert.equal(s.bpm, 128);

// Added with the overdrive tools: the meter editor_seek_bar counts bars from,
// the selection editor_loop_selection acts on, and the snapshot names
// editor_restore will accept.
assert.deepEqual(s.timeSignature, { num: 6, den: 8 });
assert.deepEqual(s.selectedClipIds, ['ca', 'cm']);
assert.deepEqual(s.snapshotNames, []);

console.log('summarizeEditor MIDI/audio kind regression passed');
