/**
 * THROWAWAY A/B harness for ticket P-20260915-batch6-T11b.
 *
 * Renders the same synthetic project twice — once through the three inline
 * bodies `WaveformEditor.tsx` had at batch-6 baseline `cce9375`
 * (`./legacyBodies.ts`, a verbatim transcription of this repo's own code) and
 * once through `src/lib/renderCore.ts` — then decodes both WAVs and reports
 * max |Δ| and RMS Δ per channel.
 *
 * Runs in a real headless Chromium (see `run.mjs`); nothing here is shipped.
 *
 * DETERMINISM: `rackEffects.makeReverbIR` fills its impulse response with
 * `Math.random()`, so two builds of the same reverb are two different rooms.
 * Every render below therefore runs under a seeded `Math.random`, reset to the
 * same seed each time — the refactor is what is being measured, not the IR
 * noise the app deliberately re-rolls.
 */
import {
  BOUNCE_SAMPLE_RATE, encodeBounce, renderBounce, renderExtentSec,
  type BounceRequest, type BounceScope, type RenderDeps,
} from '../../src/lib/renderCore';
import { decodeClipBlob } from '../../src/lib/decodeCache';
import { buildEffectChain } from '../../src/lib/rackEffects';
import { encodeWav } from '../../src/lib/wavEncode';
import { scheduleClipSources } from '../../src/state/liveMixer';
import type {
  AudioClip, EditorTrack, AutomationLane as AutomationLaneT,
} from '../../src/state/editorStore';
import type { ChainEntry } from '../../src/state/effectChainStore';
import {
  legacyCommitEdit, legacyRenderTrackStem, legacySendSelectionToInit,
  type Project, type Rendered,
} from './legacyBodies';

/* ── Deterministic RNG, so the convolution IR is the same room twice ──────── */

const REAL_RANDOM = Math.random;
const mulberry32 = (seed: number) => () => {
  seed = (seed + 0x6d2b79f5) | 0;
  let t = seed;
  t = Math.imul(t ^ (t >>> 15), t | 1);
  t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
async function seeded<T>(fn: () => Promise<T>): Promise<T> {
  Math.random = mulberry32(0x5eed);
  try { return await fn(); } finally { Math.random = REAL_RANDOM; }
}

/* ── Sources ─────────────────────────────────────────────────────────────── */

const SR = 44100;

/** A deterministic WAV of `channels` channels: a sine plus a little seeded
 *  noise, different per channel so a pan law change is audible in the diff. */
function makeWav(channels: number, seconds: number, freq: number, seed: number): Blob {
  const rnd = mulberry32(seed);
  const len = Math.round(seconds * SR);
  const ctx = new OfflineAudioContext(channels, len, SR);
  const buf = ctx.createBuffer(channels, len, SR);
  for (let ch = 0; ch < channels; ch += 1) {
    const d = buf.getChannelData(ch);
    for (let i = 0; i < len; i += 1) {
      d[i] = 0.55 * Math.sin((2 * Math.PI * (freq + ch * 37) * i) / SR) + 0.08 * (rnd() * 2 - 1);
    }
  }
  return encodeWav(buf, { float32: false });
}

const MONO = makeWav(1, 4.0, 220, 11);
const STEREO = makeWav(2, 4.0, 330, 22);
const MUTED_SRC = makeWav(2, 3.0, 440, 33);
const SOLO_SRC = makeWav(2, 3.0, 550, 44);
const VSTLESS_SRC = makeWav(1, 3.0, 660, 55);
const VSTED_SRC = makeWav(2, 3.0, 770, 66);

const clip = (o: Partial<AudioClip> & Pick<AudioClip, 'id' | 'trackId' | 'audioBlob'>): AudioClip => ({
  label: o.id,
  mimeType: 'audio/wav',
  sourceDuration: 4,
  offsetIntoSource: 0,
  durationSec: 3,
  startSec: 0,
  color: '#888',
  ...o,
} as AudioClip);

const track = (o: Partial<EditorTrack> & Pick<EditorTrack, 'id'>): EditorTrack => ({
  name: o.id,
  nameAutoGenerated: false,
  volume: 1,
  pan: 0,
  mute: false,
  solo: false,
  color: '#888',
  ...o,
});

const COMPRESSOR: ChainEntry = {
  id: 'fx-comp',
  effect: 'compressor',
  enabled: true,
  params: { threshold: -24, ratio: 4, knee: 6, attack: 10, release: 150, makeup: 3 },
};
const REVERB: ChainEntry = {
  id: 'fx-verb',
  effect: 'reverb',
  enabled: true,
  params: { decay: 1.8, predelay: 20, tone: 8000, wet: 0.35 },
};
/** A hosted VST3 entry. It never runs in the browser — both the old body and
 *  the core strip it from the rack, and the real consumer posts the stem
 *  through it on the backend afterwards. Its only effect on a bounce is that
 *  `renderTrackStem` then encodes the stem as float32 so the backend hops do
 *  not requantize, which is the branch the C cases below need covered. No
 *  request is made: neither side does the backend hops. */
const VST3: ChainEntry = {
  id: 'fx-vst3',
  effect: 'vst3',
  enabled: true,
  params: {},
  vst: { plugin_path: 'C:/fake/NotLoaded.vst3', plugin_name: 'NotLoaded' },
};

/** The project the ticket specifies: a mono clip and a stereo clip on one
 *  track, a fade in/out, a muted track, a soloed track, a track carrying the
 *  compressor and the reverb, a volume lane and an FX-param lane, and a
 *  VST-less track for the stem render. `solo` and `laneCurve` are the two
 *  dials the cases below turn. */
function buildProject(opts: { solo: boolean; laneCurve: number }): Project {
  // T1 is soloed alongside T3 in the solo variant, so the solo case still
  // renders the rack, the lanes and the mono/stereo pair instead of silencing
  // every interesting track.
  const tMain = track({
    id: 'T1', name: 'main', volume: 0.8, pan: -0.3, solo: opts.solo, fxChain: [COMPRESSOR, REVERB],
  });
  const tMuted = track({ id: 'T2', name: 'muted', mute: true, volume: 0.9, pan: 0.4 });
  const tSolo = track({ id: 'T3', name: 'soloed', solo: opts.solo, volume: 0.7, pan: 0.2 });
  const tVstless = track({ id: 'T4', name: 'vstless', volume: 0.6, pan: 0.5, fxChain: [COMPRESSOR] });
  // The float32 branch of the stem render: a rack entry the core keeps and a
  // hosted VST3 entry it strips.
  const tVsted = track({ id: 'T5', name: 'vsted', volume: 0.55, pan: -0.2, fxChain: [COMPRESSOR, VST3] });

  const clips: AudioClip[] = [
    clip({
      id: 'C1-mono', trackId: 'T1', audioBlob: MONO,
      startSec: 0.5, durationSec: 3, fadeInSec: 0.4, fadeOutSec: 0.6, gain: 0.9,
    }),
    clip({ id: 'C2-stereo', trackId: 'T1', audioBlob: STEREO, startSec: 2.0, durationSec: 3 }),
    clip({ id: 'C3-muted-track', trackId: 'T2', audioBlob: MUTED_SRC, startSec: 1.0, durationSec: 2.5 }),
    clip({ id: 'C4-solo-track', trackId: 'T3', audioBlob: SOLO_SRC, startSec: 0.8, durationSec: 2.5 }),
    clip({ id: 'C5-vstless', trackId: 'T4', audioBlob: VSTLESS_SRC, startSec: 1.5, durationSec: 2.0 }),
    clip({
      id: 'C6-vsted', trackId: 'T5', audioBlob: VSTED_SRC,
      startSec: 0.3, durationSec: 2.4, fadeInSec: 0.3, fadeOutSec: 0.3,
    }),
  ];

  const automationLanes: AutomationLaneT[] = [
    {
      id: 'L-vol', enabled: true,
      target: { kind: 'trackVolume', trackId: 'T1' },
      points: [
        { t: 0, v: 0.3, curve: opts.laneCurve },
        { t: 2.5, v: 1.0, curve: opts.laneCurve },
        { t: 5.0, v: 0.5 },
      ],
    },
    {
      // The other caller of renderCore's `scheduleParamLane`, so both are
      // measured. Out of range on purpose: the clamp has to reach inside the
      // rasterised curve, not just its endpoints.
      id: 'L-pan', enabled: true,
      target: { kind: 'trackPan', trackId: 'T1' },
      points: [
        { t: 0.2, v: -1.4, curve: -opts.laneCurve },
        { t: 3.5, v: 1.4 },
      ],
    },
    {
      id: 'L-fx', enabled: true,
      target: { kind: 'trackFx', trackId: 'T1', entryId: 'fx-comp', paramKey: 'threshold' },
      points: [
        { t: 0, v: -12 },
        { t: 3.0, v: -40 },
      ],
    },
  ];

  return {
    clips,
    tracks: [tMain, tMuted, tSolo, tVstless, tVsted],
    masterFxChain: [REVERB],
    automationLanes,
  };
}

/* ── The new path: exactly the deps `WaveformEditor.renderDeps()` builds ──── */

const depsFor = (p: Project): RenderDeps => ({
  clips: p.clips,
  tracks: p.tracks,
  masterFxChain: p.masterFxChain,
  automationLanes: p.automationLanes,
  decode: decodeClipBlob,
  buildChain: buildEffectChain,
  scheduleSources: scheduleClipSources,
});

async function core(p: Project, req: BounceRequest): Promise<{ blob: Blob; rendered: AudioBuffer }> {
  const rendered = await renderBounce(req, depsFor(p));
  return { blob: encodeBounce(rendered, req), rendered };
}

/* ── Compare ─────────────────────────────────────────────────────────────── */

interface Delta { channel: number; maxAbs: number; rms: number; samples: number }

interface Diff {
  deltas: Delta[];
  /** Set when the two sides are not the same shape. A truncating compare would
   *  otherwise report a tiny delta over the overlap and say nothing about the
   *  samples one side does not have — so this is a hard FAILURE in `run.mjs`,
   *  never a note. A render that is the wrong LENGTH is the wrong render. */
  mismatch?: string;
}

/** Diff two AudioBuffers — the render itself, before the 16-bit encode. A
 *  difference of exactly 2^-15 (3.05e-5) in the file domain is one PCM16 LSB
 *  and says nothing about the render; this says what the render actually did. */
function diffBuffers(label: string, a: AudioBuffer, b: AudioBuffer): Diff {
  const mismatch = (a.length !== b.length || a.numberOfChannels !== b.numberOfChannels)
    ? `SHAPE MISMATCH (${label}) legacy=${a.numberOfChannels}x${a.length} core=${b.numberOfChannels}x${b.length}`
    : undefined;
  const chans = Math.min(a.numberOfChannels, b.numberOfChannels);
  const n = Math.min(a.length, b.length);
  const deltas: Delta[] = [];
  for (let ch = 0; ch < chans; ch += 1) {
    const da = a.getChannelData(ch);
    const db = b.getChannelData(ch);
    let maxAbs = 0;
    let sum = 0;
    for (let i = 0; i < n; i += 1) {
      const d = Math.abs(da[i] - db[i]);
      if (d > maxAbs) maxAbs = d;
      sum += d * d;
    }
    deltas.push({ channel: ch, maxAbs, rms: Math.sqrt(sum / n), samples: n });
  }
  return { deltas, mismatch };
}

async function compare(a: Blob, b: Blob): Promise<Diff> {
  const ctx = new AudioContext({ sampleRate: SR });
  try {
    const [ba, bb] = await Promise.all([
      ctx.decodeAudioData(await a.arrayBuffer()),
      ctx.decodeAudioData(await b.arrayBuffer()),
    ]);
    return diffBuffers('wav', ba, bb);
  } finally {
    ctx.close().catch(() => {});
  }
}

/* ── Cases ───────────────────────────────────────────────────────────────── */

interface CaseResult {
  renderer: 'A' | 'B' | 'C';
  name: string;
  /** Diff of the WAV files the app writes (16-bit PCM for all three today). */
  deltas: Delta[];
  /** Diff of the rendered AudioBuffers, before any encode. */
  floatDeltas: Delta[];
  /** Every shape disagreement found, in either domain. Non-empty = the case
   *  FAILS, whatever the deltas over the overlap say. */
  mismatches: string[];
  extra?: string;
  error?: string;
}

async function runCases(): Promise<CaseResult[]> {
  const out: CaseResult[] = [];
  const add = async (
    renderer: 'A' | 'B' | 'C', name: string,
    run: () => Promise<{ legacy: Rendered; core: Rendered; extra?: string }>,
  ) => {
    try {
      const { legacy, core: c, extra } = await run();
      const wav = await compare(legacy.blob, c.blob);
      const floats = diffBuffers('render', legacy.rendered, c.rendered);
      out.push({
        renderer, name, deltas: wav.deltas, floatDeltas: floats.deltas, extra,
        mismatches: [wav.mismatch, floats.mismatch].filter((m): m is string => m != null),
      });
    } catch (e) {
      out.push({
        renderer, name, deltas: [], floatDeltas: [], mismatches: [],
        error: e instanceof Error ? `${e.message}\n${e.stack}` : String(e),
      });
    }
  };

  /* A — selection. `includeTrackMix: true`, and solo must be IGNORED, so the
     soloed project is the one that proves it. */
  for (const solo of [false, true]) {
    await add('A', `selection · mono+stereo+fades+muted-track · solo=${solo}`, async () => {
      const p = buildProject({ solo, laneCurve: 0 });
      // The selection the editor would hand over: both T1 clips, plus the clip
      // on the muted track (A honours mute) and the one on the soloed track
      // (A ignores solo).
      const selection = p.clips.filter((c) => ['C1-mono', 'C2-stereo', 'C3-muted-track', 'C4-solo-track'].includes(c.id));
      const scope: BounceScope = { kind: 'selection', clipIds: selection.map((c) => c.id) };
      const req: BounceRequest = {
        scope, sampleRate: BOUNCE_SAMPLE_RATE,
        includeFx: false, includeAutomation: false, includeTrackMix: true, float32: false,
      };
      const legacy = await seeded(() => legacySendSelectionToInit(p, selection));
      const c = await seeded(() => core(p, req));
      return { legacy, core: c };
    });
  }

  /* B — master. Two solo states, and a linear vs curved volume lane. */
  for (const solo of [false, true]) {
    for (const laneCurve of [0, 0.7]) {
      await add('B', `master · compressor+reverb · volLane(curve=${laneCurve}) + fxLane · solo=${solo}`, async () => {
        const p = buildProject({ solo, laneCurve });
        const req: BounceRequest = {
          scope: { kind: 'master' }, sampleRate: BOUNCE_SAMPLE_RATE,
          includeFx: true, includeAutomation: true, includeTrackMix: true, float32: false,
        };
        const legacy = await seeded(() => legacyCommitEdit(p));
        const c = await seeded(() => core(p, req));
        return { legacy, core: c };
      });
    }
  }

  /* C — track stem, on the VST-less track (float32 === false) and on the
     rack-heavy track. Automation must NOT apply, the track mix must NOT apply. */
  const stemCases: Record<string, string> = {
    T4: 'VST-less, compressor — float32=false',
    T1: 'compressor+reverb — float32=false',
    T5: 'compressor + an enabled VST3 entry — float32=TRUE',
  };
  for (const trackId of ['T4', 'T1', 'T5']) {
    await add('C', `stem · ${trackId} · ${stemCases[trackId]}`, async () => {
      const p = buildProject({ solo: false, laneCurve: 0 });
      const trk = p.tracks.find((t) => t.id === trackId)!;
      const vsts = (trk.fxChain ?? []).filter((e) => e.enabled && e.effect === 'vst3' && e.vst);
      const scope: BounceScope = { kind: 'track', trackId };
      const req: BounceRequest = {
        scope, sampleRate: BOUNCE_SAMPLE_RATE,
        includeFx: true, includeAutomation: false, includeTrackMix: false,
        float32: vsts.length > 0,
      };
      const legacy = await seeded(() => legacyRenderTrackStem(p, trackId));
      const c = await seeded(() => core(p, req));
      const coreDur = renderExtentSec(p.clips, scope);
      return {
        legacy, core: c,
        extra: `durationSec legacy=${legacy.durationSec} core=${coreDur} float32=${vsts.length > 0}`,
      };
    });
  }

  return out;
}

declare global {
  interface Window { __AB__?: CaseResult[]; __AB_ERR__?: string }
}

runCases()
  .then((r) => { window.__AB__ = r; })
  .catch((e) => { window.__AB_ERR__ = e instanceof Error ? `${e.message}\n${e.stack}` : String(e); });
