/**
 * The editor store's tool-facing extensions, driven as the real zustand store.
 *
 * `editorTools` is an imperative facade over exactly these actions, so what is
 * pinned here is the contract the facade leans on: that a multi-clip selection
 * keeps the single-select field usable for the components that still read it,
 * that a time signature is document state (it rides undo, and a load replaces
 * it), that reordering and duplicating tracks go through the store rather than
 * being re-implemented per caller, and that NAMED snapshots sit outside undo —
 * a snapshot is a bookmark you take before an experiment, and having it eat an
 * undo step would defeat the point of taking one.
 *
 * Run: `npx tsx src/state/editorStore.test.ts`
 */
import assert from 'node:assert/strict';
import { useEditorStore } from './editorStore';
import type { AudioClip, EditorTrack } from './editorStore';

const blob = () => new Blob(['pcm'], { type: 'audio/wav' });

/** Longer than the store's HISTORY_COALESCE_MS, so the next edit opens a new
 *  undo step instead of folding into the previous one. */
const settle = () => new Promise((r) => setTimeout(r, 340));

const track = (id: string, over: Partial<EditorTrack> = {}): EditorTrack => ({
  id,
  name: id,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#8b5cf6',
  ...over,
});

const clip = (id: string, trackId: string, over: Partial<AudioClip> = {}): AudioClip => ({
  id,
  trackId,
  label: id,
  audioBlob: blob(),
  mimeType: 'audio/wav',
  sourceDuration: 4,
  offsetIntoSource: 0,
  durationSec: 4,
  startSec: 0,
  color: '#8b5cf6',
  ...over,
});

/** A fresh three-track / three-clip document. `loadProject` resets history, so
 *  every block below starts from a known undo depth of zero. */
const seed = () => {
  useEditorStore.getState().loadProject({
    tracks: [track('t1'), track('t2'), track('t3')],
    clips: [clip('c1', 't1'), clip('c2', 't1', { startSec: 8 }), clip('c3', 't2')],
    bpm: 120,
  });
};

/* ── multi-select mirrors the single-select field ────────────────────────── */
{
  seed();
  const st = useEditorStore.getState();
  st.setSelectedClips(['c2', 'c3', 'c2']);

  const after = useEditorStore.getState();
  assert.deepEqual(after.selectedClipIds, ['c2', 'c3'], 'duplicates collapse');
  assert.equal(after.selectedClipId, 'c2', 'the first id stays readable by single-select consumers');

  after.setSelectedClips([]);
  assert.deepEqual(useEditorStore.getState().selectedClipIds, []);
  assert.equal(useEditorStore.getState().selectedClipId, null, 'an empty selection clears, not strands');

  // The legacy single setter keeps working and narrows the multi-selection to
  // the one clip, so the two fields can never disagree.
  useEditorStore.getState().setSelected('c1');
  assert.deepEqual(useEditorStore.getState().selectedClipIds, ['c1']);
  useEditorStore.getState().setSelected(null);
  assert.deepEqual(useEditorStore.getState().selectedClipIds, []);
}

/* ── time signature: document state, validated ───────────────────────────── */
{
  seed();
  assert.deepEqual(useEditorStore.getState().timeSignature, { num: 4, den: 4 }, 'defaults to 4/4');

  useEditorStore.getState().setTimeSignature(7, 8);
  assert.deepEqual(useEditorStore.getState().timeSignature, { num: 7, den: 8 });

  // Nonsense is refused outright rather than clamped into something the caller
  // never asked for — a silently substituted meter would re-bar the whole song.
  for (const [num, den] of [[0, 4], [4, 5], [4, 0], [NaN, 4], [4.5, 4], [33, 4]] as const) {
    useEditorStore.getState().setTimeSignature(num, den);
    assert.deepEqual(
      useEditorStore.getState().timeSignature,
      { num: 7, den: 8 },
      `${num}/${den} should have been refused`,
    );
  }

  // It rides undo with the rest of the document.
  useEditorStore.getState().undo();
  assert.deepEqual(useEditorStore.getState().timeSignature, { num: 4, den: 4 });
  useEditorStore.getState().redo();
  assert.deepEqual(useEditorStore.getState().timeSignature, { num: 7, den: 8 });

  // A load carries it; a load without one keeps what is set, exactly as bpm does.
  useEditorStore.getState().loadProject({ tracks: [track('t1')], clips: [], bpm: 90, timeSignature: { num: 3, den: 4 } });
  assert.deepEqual(useEditorStore.getState().timeSignature, { num: 3, den: 4 });
  useEditorStore.getState().loadProject({ tracks: [track('t1')], clips: [] });
  assert.deepEqual(useEditorStore.getState().timeSignature, { num: 3, den: 4 });
}

/* ── reorderTracks ───────────────────────────────────────────────────────── */
{
  seed();
  useEditorStore.getState().reorderTracks(['t3', 't1', 't2']);
  assert.deepEqual(useEditorStore.getState().tracks.map((t) => t.id), ['t3', 't1', 't2']);

  // A partial list is a "move these to the front"; the rest keep their order,
  // so "put the drums on top" does not have to enumerate the whole session.
  useEditorStore.getState().reorderTracks(['t2']);
  assert.deepEqual(useEditorStore.getState().tracks.map((t) => t.id), ['t2', 't3', 't1']);

  // Unknown ids are ignored rather than dropping tracks out of the document.
  useEditorStore.getState().reorderTracks(['nope', 't1']);
  assert.deepEqual(useEditorStore.getState().tracks.map((t) => t.id), ['t1', 't2', 't3']);
  assert.equal(useEditorStore.getState().tracks.length, 3);
}

/* ── duplicateTrack deep-copies the clips ────────────────────────────────── */
{
  seed();
  const newId = useEditorStore.getState().duplicateTrack('t1');
  assert.ok(newId, 'returns the new track id');

  const st = useEditorStore.getState();
  assert.equal(st.tracks.length, 4);
  assert.equal(st.tracks[1].id, newId, 'the copy lands directly under the original');
  assert.equal(st.tracks[1].name, 't1 copy');

  const copies = st.clips.filter((c) => c.trackId === newId);
  assert.equal(copies.length, 2, 'both of t1s clips came along');
  assert.equal(copies.filter((c) => c.id === 'c1' || c.id === 'c2').length, 0, 'the copies get fresh ids');
  assert.equal(copies[0].startSec, 0);
  assert.equal(copies[1].startSec, 8, 'timeline positions are preserved');
  assert.equal(copies[0].audioBlob, st.clips[0].audioBlob, 'the audio is shared, not re-encoded');

  // Editing a copy must not reach back into the original.
  useEditorStore.getState().updateClip(copies[0].id, { label: 'moved' });
  assert.equal(useEditorStore.getState().clips.find((c) => c.id === 'c1').label, 'c1');

  assert.equal(useEditorStore.getState().duplicateTrack('ghost'), null);
}

/* ── named snapshots sit outside undo history ────────────────────────────── */
{
  seed();
  useEditorStore.getState().takeSnapshot('before');
  assert.deepEqual(useEditorStore.getState().listSnapshots(), ['before']);
  assert.equal(useEditorStore.getState()._undo.length, 0, 'taking a snapshot is not an edit');

  useEditorStore.getState().removeClip('c1');
  useEditorStore.getState().setBpm(140);
  assert.equal(useEditorStore.getState().clips.length, 2);

  // The store folds document changes made within HISTORY_COALESCE_MS into ONE
  // undo step (so a clip drag is one step, not sixty). A test that runs in a
  // millisecond therefore has to wait if it wants two separate steps.
  await settle();

  assert.equal(useEditorStore.getState().restoreSnapshot('before'), true);
  const restored = useEditorStore.getState();
  assert.equal(restored.clips.length, 3, 'the deleted clip is back');
  assert.equal(restored.bpm, 120, 'and so is the tempo it was taken at');

  // A restore IS an edit, so it can itself be undone back to where the user was
  // standing when they asked for it.
  assert.ok(useEditorStore.getState()._undo.length > 0);
  useEditorStore.getState().undo();
  assert.equal(useEditorStore.getState().clips.length, 2);
  assert.equal(useEditorStore.getState().bpm, 140);

  assert.equal(useEditorStore.getState().restoreSnapshot('nope'), false);

  // Snapshots reference the tracks and clips of the project they were taken in,
  // so a different project must not be able to restore into them.
  useEditorStore.getState().loadProject({ tracks: [track('t1')], clips: [] });
  assert.deepEqual(useEditorStore.getState().listSnapshots(), []);
}

/* ── undo groups: one step per group, independent of the coalescing window ── */

const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));
const depth = () => useEditorStore.getState()._undo.length;
const label = (id: string) => useEditorStore.getState().clips.find((c) => c.id === id)?.label;

{
  // A user edit 50 ms before a grouped write is well inside HISTORY_COALESCE_MS,
  // so without a forced boundary the two would fold into ONE step and undoing
  // the tool would silently take the user's edit with it.
  seed();
  useEditorStore.getState().updateClip('c1', { label: 'user edit' });
  assert.equal(depth(), 1);
  await wait(50);

  const st = useEditorStore.getState();
  st.beginUndoGroup();
  st.updateClip('c2', { label: 'tool edit' });
  st.endUndoGroup();

  assert.equal(depth(), 2, 'the group opened its own step instead of joining the user edit');
  useEditorStore.getState().undo();
  assert.equal(label('c2'), 'c2', 'undo reverted the grouped write');
  assert.equal(label('c1'), 'user edit', 'and left the user edit alone');
}

{
  // A slow group — 400 ms between writes, longer than the coalescing window —
  // is still one step.
  seed();
  const st = useEditorStore.getState();
  st.beginUndoGroup();
  st.updateClip('c1', { label: 'first' });
  await wait(400);
  useEditorStore.getState().updateClip('c2', { label: 'second' });
  useEditorStore.getState().endUndoGroup();

  assert.equal(depth(), 1, 'two writes 400 ms apart, one step');
  useEditorStore.getState().undo();
  assert.equal(label('c1'), 'c1');
  assert.equal(label('c2'), 'c2', 'one undo reverted both writes');
}

{
  // The boundary is on BOTH sides: an edit 50 ms after the group ends is its own
  // step, not folded into the group's.
  seed();
  useEditorStore.getState().undoGroup(() => {
    useEditorStore.getState().updateClip('c1', { label: 'tool' });
  });
  await wait(50);
  useEditorStore.getState().updateClip('c2', { label: 'user after' });
  assert.equal(depth(), 2);
  useEditorStore.getState().undo();
  assert.equal(label('c2'), 'c2');
  assert.equal(label('c1'), 'tool', 'the group survived undoing the later edit');
}

{
  // undoGroup returns what its function returns, and nested groups are one step.
  seed();
  const out = useEditorStore.getState().undoGroup(() => {
    useEditorStore.getState().updateClip('c1', { label: 'outer' });
    return useEditorStore.getState().undoGroup(() => {
      useEditorStore.getState().updateClip('c2', { label: 'inner' });
      return 42;
    });
  });
  assert.equal(out, 42);
  assert.equal(depth(), 1, 'a nested group does not open a second step');

  // An async function keeps the group open until it settles.
  seed();
  await useEditorStore.getState().undoGroup(async () => {
    useEditorStore.getState().updateClip('c1', { label: 'a' });
    await wait(400);
    useEditorStore.getState().updateClip('c2', { label: 'b' });
  });
  assert.equal(depth(), 1, 'an awaited 400 ms gap inside an async group is still one step');
}

{
  // A throwing group still closes: afterwards edits 400 ms apart are separate
  // steps again (a group left open would have swallowed them into one).
  seed();
  assert.throws(() =>
    useEditorStore.getState().undoGroup(() => {
      useEditorStore.getState().updateClip('c1', { label: 'partial' });
      throw new Error('boom');
    }),
  /boom/);
  await wait(400);
  useEditorStore.getState().updateClip('c2', { label: 'x' });
  await wait(400);
  useEditorStore.getState().updateClip('c3', { label: 'y' });
  assert.equal(depth(), 3, 'the partial group, then two independent edits');

  // An unmatched end is a no-op rather than driving the depth negative.
  useEditorStore.getState().endUndoGroup();
  useEditorStore.getState().endUndoGroup();
  await wait(400);
  useEditorStore.getState().updateClip('c1', { label: 'z' });
  assert.equal(depth(), 4);

  // A group that writes nothing records nothing.
  useEditorStore.getState().undoGroup(() => undefined);
  assert.equal(depth(), 4);
}

console.log('editorStore extensions: ok');
