/**
 * The EDIT autosave manifest must round-trip the project meter.
 *
 * `timeSignature` is document state (it rides undo alongside bpm), so a meter
 * the user — or the assistant, via `editor_set_time_signature` — sets has to
 * survive a crash-recovery restore exactly as the tempo does. It did not: the
 * manifest never wrote the field and the restore called `loadProject` without
 * it, so a 7/8 session came back in whatever meter the fresh session happened
 * to hold.
 *
 * The suite drives the REAL module against an in-memory OPFS and an immediate
 * `window.setTimeout`, so what is pinned is the actual save/restore path rather
 * than a re-implementation of it.
 *
 * Run: `npx tsx src/lib/editorAutosave.test.ts`
 */
import assert from 'node:assert/strict';

// ── In-memory OPFS ───────────────────────────────────────────────────────────

class FakeWritable {
  private chunks: Array<Uint8Array> = [];
  constructor(private readonly onClose: (bytes: Uint8Array) => void) {}
  async write(data: string | Blob | ArrayBuffer | Uint8Array): Promise<void> {
    if (typeof data === 'string') {
      this.chunks.push(new TextEncoder().encode(data));
    } else if (data instanceof Uint8Array) {
      this.chunks.push(data);
    } else if (data instanceof ArrayBuffer) {
      this.chunks.push(new Uint8Array(data));
    } else {
      this.chunks.push(new Uint8Array(await data.arrayBuffer()));
    }
  }
  async close(): Promise<void> {
    const total = this.chunks.reduce((n, c) => n + c.byteLength, 0);
    const out = new Uint8Array(total);
    let at = 0;
    for (const c of this.chunks) {
      out.set(c, at);
      at += c.byteLength;
    }
    this.onClose(out);
  }
}

class FakeFileHandle {
  bytes = new Uint8Array();
  async getFile(): Promise<{ text(): Promise<string>; arrayBuffer(): Promise<ArrayBuffer> }> {
    const bytes = this.bytes;
    return {
      text: async () => new TextDecoder().decode(bytes),
      arrayBuffer: async () => bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer,
    };
  }
  async createWritable(): Promise<FakeWritable> {
    return new FakeWritable((bytes) => {
      this.bytes = bytes;
    });
  }
}

class FakeDir {
  files = new Map<string, FakeFileHandle>();
  dirs = new Map<string, FakeDir>();
  async getDirectoryHandle(name: string, opts?: { create?: boolean }): Promise<FakeDir> {
    let d = this.dirs.get(name);
    if (!d) {
      if (!opts?.create) throw new Error(`NotFoundError: ${name}`);
      d = new FakeDir();
      this.dirs.set(name, d);
    }
    return d;
  }
  async getFileHandle(name: string, opts?: { create?: boolean }): Promise<FakeFileHandle> {
    let f = this.files.get(name);
    if (!f) {
      if (!opts?.create) throw new Error(`NotFoundError: ${name}`);
      f = new FakeFileHandle();
      this.files.set(name, f);
    }
    return f;
  }
  async removeEntry(name: string, opts?: { recursive?: boolean }): Promise<void> {
    void opts;
    this.files.delete(name);
    this.dirs.delete(name);
  }
  async *keys(): AsyncIterable<string> {
    for (const k of this.files.keys()) yield k;
    for (const k of this.dirs.keys()) yield k;
  }
}

const opfsRoot = new FakeDir();

Object.defineProperty(globalThis, 'navigator', {
  configurable: true,
  value: { storage: { getDirectory: async () => opfsRoot } },
});

// The save driver debounces through `window.setTimeout`; fire on the next tick
// so the suite pins the save path itself, not the 2s debounce.
Object.defineProperty(globalThis, 'window', {
  configurable: true,
  value: {
    setTimeout: (fn: () => void) => setTimeout(fn, 0) as unknown as number,
    clearTimeout: (id: number) => clearTimeout(id as unknown as NodeJS.Timeout),
  },
});

const { useEditorStore } = await import('../state/editorStore');
const { initEditorAutosave, useAutosaveRecoveryStore } = await import('./editorAutosave');

/** The module's own OPFS layout (module-private constants there). */
const AUTOSAVE_DIR_NAME = 'thedaw-editor-autosave';
const AUTOSAVE_MANIFEST_NAME = 'manifest.json';

type EditorTrack = import('../state/editorStore').EditorTrack;
type AudioClip = import('../state/editorStore').AudioClip;

const track = (id: string): EditorTrack => ({
  id,
  name: id,
  nameAutoGenerated: false,
  volume: 0.8,
  pan: 0,
  mute: false,
  solo: false,
  color: '#8b5cf6',
});

const clip = (id: string, trackId: string): AudioClip => ({
  id,
  trackId,
  label: id,
  audioBlob: new Blob(['pcm'], { type: 'audio/wav' }),
  mimeType: 'audio/wav',
  sourceDuration: 4,
  offsetIntoSource: 0,
  durationSec: 4,
  startSec: 0,
  color: '#8b5cf6',
});

const tick = (ms = 20) => new Promise((r) => setTimeout(r, ms));

async function manifestHandle(): Promise<FakeFileHandle> {
  const dir = await opfsRoot.getDirectoryHandle(AUTOSAVE_DIR_NAME, { create: true });
  return dir.getFileHandle(AUTOSAVE_MANIFEST_NAME, { create: true });
}

const readManifestJson = async (): Promise<Record<string, unknown>> =>
  JSON.parse(new TextDecoder().decode((await manifestHandle()).bytes)) as Record<string, unknown>;

async function writeManifest(bytes: Uint8Array): Promise<void> {
  const w = await (await manifestHandle()).createWritable();
  await w.write(bytes);
  await w.close();
}

/** The 7/8 manifest the first block writes, reused by the legacy block. */
let saved = new Uint8Array();

/* ── the meter survives a save → restore round trip ───────────────────────── */
{
  initEditorAutosave();
  await tick(); // let the "no manifest yet" probe resume saving

  useEditorStore.getState().loadProject({
    tracks: [track('t1')],
    clips: [clip('c1', 't1')],
    bpm: 132,
    timeSignature: { num: 7, den: 8 },
  });

  // Wait for the debounced save to land the manifest.
  for (let i = 0; i < 60 && (await manifestHandle()).bytes.byteLength === 0; i += 1) await tick(10);
  const manifest = await readManifestJson();
  assert.deepEqual(
    manifest.timeSignature,
    { num: 7, den: 8 },
    'the autosave manifest must carry the project meter',
  );

  // Keep the 7/8 document on disk, then land the session in a different meter
  // (the clip stays, so the asset GC keeps its bytes) and restore.
  saved = (await manifestHandle()).bytes;
  useEditorStore.getState().setTimeSignature(3, 4);
  await tick(60);
  await writeManifest(saved);

  await useAutosaveRecoveryStore.getState().restore();
  assert.deepEqual(
    useEditorStore.getState().timeSignature,
    { num: 7, den: 8 },
    'a restored autosave must bring its own meter back',
  );
}

/* ── a legacy manifest (no meter) restores as 4/4 ─────────────────────────── */
{
  await tick(60); // let the restore's own autosave land before overwriting it
  const legacy = JSON.parse(new TextDecoder().decode(saved)) as Record<string, unknown>;
  delete legacy.timeSignature;
  await writeManifest(new TextEncoder().encode(JSON.stringify(legacy)));

  await useAutosaveRecoveryStore.getState().restore();
  assert.deepEqual(
    useEditorStore.getState().timeSignature,
    { num: 4, den: 4 },
    'a document written before the field existed is 4/4, not whatever the session held',
  );
}

console.log('editorAutosave meter round-trip: ok');
